### ISSUE TITLE
지금 북마크에 링크주소를 편집해서 실행하면 올바르지 않은 요청이라고 뜹니다.

### ISSUE THREAD

**Issue by codebakery-pandha** [inha-downloader/support#1]
고생 많으십니다.

휴일인데 이 방법을 시도한 제 자신이 불쌍해지는 하루가 아닐 수 없습니다.

지금 북마크에 링크주소를 편집해서 실행하면 올바르지 않은 요청이라고 알림 메시지가 뜨며 실행이 되지 않습니다.

현재 ffmpeg를 통한 방법은 아직 막히지 않은듯하니.. 전 우선은 그 방법을 쓰겠습니다. 시간날때 수정해주시면 정말 잘 사용하겠습니당..헤헤..

**Comment by inha-downloader** [comment]
혹시 링크주소를 편집해서 실행한다는게 무슨 말씀이신지요? 만약 게시글에 작성된 대로 하셨으면 아직 정상 작동합니다. 

'올바르지 않은 요청입니다' 라는 메시지는 다운로드를 위해 필요한 JS파일이 정상적이지 않은 경로에서 불러와졌을 때 표시됩니다. 하지만 일부 브라우저의 JS 처리 방식에 따라 의도되지 않은 방법으로 작동될 수 있습니다.

혹시 타 브라우저를 사용하셨다면 크롬 브라우저로 시도 후 업데이트 부탁드립니다. 또한 사용하신 브라우저와 OS 환경 (Windows 10/macOS Catalina/Ubuntu 20.04/etc.)도 남겨주시면 디버깅에 도움 될 것 같습니다.

**Comment by codebakery-pandha** [comment]
말 그대로입니다. 북마크 주소를 편집하여, 링크주소 복사하기 실행 후 붙여넣기 한 다음 해당 북마크를 실행하면 강의 페이지에서 바로 강의영상 다운로드 버튼이 표시가 되었던걸로 기억하는데, 지금은 일련의 과정을 거친다음 실행하면 올바르지 않은 요청이라고 뜹니다. 현재 크롬 브라우저 최신버전 사용중이며, Windows 10 edu 버전 사용중입니다.

**Comment by inha-downloader** [comment]
혹시 해당 부분 원격으로 확인 해 봐 드려도 될까요? 가능하시다면 에브리타임 쪽지나 메일 부탁드립니다

**Comment by codebakery-pandha** [comment]
pandha12@naver.com 입니다.  연락 부탁드립니다.
